### ISSUE TITLE
[BUG] Getting an error when trying to sync from linux

### ISSUE THREAD

**Issue by harshg-db** [databricks/databricks-vscode#1318]
**Describe the bug**
Getting an error when trying to sync from linux

**To Reproduce**
1. Use VSCode to ssh into a linux box
2. Open a directory in VSCode
3. Try to sync files to a cluster using OAuth
4. Notice: you get the error below after a while

**Screenshots**
Stack trace
```
Login failed with Databricks CLI failed: Loading "original-fs" failed Error:Cannot find module 'original-fs' Require stack: - /home/harsh.goyal/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/server-cli.js at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15) at Module._load (node:internal/modules/cjs/loader:986:27) at Module.require (node:internal/modules/cjs/loader:1233:19) at require (node:internal/modules/helpers:179:18) at i (/home/harsh.goyal/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/server-cli.js:3:98) at r.load (/home/harsh.goyal/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/server-cli.js:2:1637) at h.load (/home/harsh.goyal/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/out/server-cli.js:1:13958) at u (/home/harsh.goyal/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41...
```

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
```
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z (5 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```
5. Databricks Extension Version: `v1.3.1`

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

Unfortunately going to "open full logs" via the command palette did nothing for me. I verified that logs are enabled.

**Additional context**

**Comment by AndreasBoegh** [comment]
Getting the same error. Cannot OAuth to Databricks (U2M).

If I run the OAuth through CLI outside extension (and dev container) everything works fine as a workaround.

**Comment by harshg-db** [comment]
Across the industry, coding is moving to remote servers. Please consider at least providing a helpful error message when the user is trying to sync a virtual file system.
